### ISSUE TITLE
Get AllContributors bot set up for this

### ISSUE THREAD

**Issue by clarkio** [Team-TAU/tau-client-js#1]

**Comment by mtfoley** [comment]
Haven't done this before but would love to learn. Let me know how I could help!

**Comment by mtfoley** [comment]
@clarkio I started PR #2 for this. when I begin following the instructions for installing the bot, it looks like I can install it for Team-TAU on this repo. Wanted to get with you first. Let me know if you see any issues with this.

**Comment by clarkio** [comment]
No issues. If it lets you install the bot go for it. I thought we might need to have an Admin approve it before we'd have access.

**Comment by mtfoley** [comment]
Awesome. I filled out the request to install the bot for this repo so I assume that @FiniteSingularity will get it to approve.

**Comment by FiniteSingularity** [comment]
Approved!
